import { Activity, Ambulance, Building2, Check, Info, Menu, Users, X } from 'lucide-react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useState, type ReactNode } from 'react';
import { useDemoStore } from './store';
import type { Role, Tone } from './types';

const tones: Record<Tone, string> = { green: 'bg-emerald-50 text-emerald-700 border-emerald-200', amber: 'bg-amber-50 text-amber-700 border-amber-200', red: 'bg-rose-50 text-rose-700 border-rose-200', blue: 'bg-blue-50 text-blue-700 border-blue-200', slate: 'bg-slate-50 text-slate-600 border-slate-200' };
export function StatusBadge({ tone = 'slate', children }: { tone?: Tone; children: ReactNode }) { return <span className={`inline-flex items-center gap-1.5 rounded-md border px-2 py-1 text-[11px] font-semibold ${tones[tone]}`}><i aria-hidden className={`h-1.5 w-1.5 rounded-full ${tone === 'green' ? 'bg-emerald-500' : tone === 'amber' ? 'bg-amber-500' : tone === 'red' ? 'bg-rose-500' : 'bg-blue-500'}`} />{children}</span>; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { if (!open) return null; return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={event => event.stopPropagation()}><div className="flex justify-between"><h2 id="modal-title" className="font-bold">{title}</h2><button onClick={onClose} aria-label="Close dialog"><X size={18}/></button></div><div className="mt-4 text-sm text-slate-600">{children}</div></section></div>; }
export function Toast() { const { toast } = useDemoStore(); return toast ? <div className={`toast ${tones[toast.tone]}`} role="status" aria-live="polite"><Check size={16}/>{toast.message}</div> : null; }

const links: Record<Role, [string, string][]> = { paramedic: [['Overview', '/paramedic/overview'], ['New Emergency', '/paramedic/new-emergency'], ['Active Case', '/paramedic/active-case'], ['Hospital Network', '/paramedic/hospital-network'], ['Resource Requests', '/paramedic/resource-requests'], ['Activity', '/paramedic/activity'], ['Help & Safety', '/help-safety']], hospital: [['Hospital Overview', '/hospital/overview'], ['Capacity', '/hospital/capacity'], ['Incoming Cases', '/hospital/incoming-cases'], ['Resource Exchange', '/hospital/resource-exchange'], ['Transfer Requests', '/hospital/transfer-requests'], ['Audit Log', '/hospital/audit-log']], admin: [['Network Overview', '/admin/overview'], ['Participating Hospitals', '/admin/participating-hospitals'], ['Capacity Freshness', '/admin/capacity-freshness'], ['Resource Requests', '/admin/resource-requests'], ['Audit & Safety', '/admin/audit-safety'], ['Settings', '/admin/settings']] };
const homes: Record<Role, string> = { paramedic: '/paramedic/overview', hospital: '/hospital/overview', admin: '/admin/overview' };
function Brand() { return <div className="flex items-center gap-3 px-5 py-5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#1677c8] text-white"><Activity size={20}/></span><div><b className="text-lg text-slate-900">MEDIMATCH</b><p className="text-[10px] uppercase tracking-wider text-slate-400">Emergency coordination</p></div></div>; }

export function AppShell() { const { role, setRole, hospitals, resetDemo } = useDemoStore(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const select = (next: Role) => { setRole(next); navigate(homes[next]); setOpen(false); }; return <div className="min-h-screen bg-slate-50"><a className="sr-only z-50 rounded bg-white p-3 text-sm font-semibold text-[#1677c8] focus:not-sr-only focus:fixed focus:left-3 focus:top-3" href="#main-content">Skip to content</a><div className="banner"><span>DEMO MODE</span><p>Prototype data — not for clinical use. All hospital data is simulated.</p><button onClick={resetDemo}>Reset demo</button></div><div className="flex"><aside className={`sidebar ${open ? 'sidebar-open' : ''}`} aria-label="Application navigation"><Brand/><div className="px-3"><p className="label">Demo role</p><div className="mt-2 grid grid-cols-3 gap-1">{([['paramedic', 'Paramedic', Ambulance], ['hospital', 'Hospital', Building2], ['admin', 'Admin', Users]] as const).map(([id, label, Icon]) => <button key={id} onClick={() => select(id)} aria-pressed={role === id} className={`role ${role === id ? 'role-active' : ''}`}><Icon size={15}/>{label}</button>)}</div></div><nav className="mt-4 border-t border-slate-100 p-3" aria-label={`${role} navigation`}>{links[role].map(([label, to]) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => `nav ${isActive ? 'nav-active' : ''}`}>{label}</NavLink>)}</nav><div className="mt-auto p-4 text-xs text-slate-500"><div className="rounded-lg bg-slate-50 p-3"><div className="mb-2 flex justify-between"><b className="text-slate-700">Network status</b><StatusBadge tone="green">Connected</StatusBadge></div>{hospitals.reduce((sum, hospital) => sum + hospital.icuBeds, 0)} reported ICU beds across {hospitals.length} facilities</div></div></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-4 sm:px-7"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}><Menu/></button><div><p className="text-xs font-semibold text-[#1677c8]">{role === 'paramedic' ? 'FIELD OPERATIONS' : role === 'hospital' ? 'HOSPITAL OPERATIONS' : 'NETWORK ADMINISTRATION'}</p><p className="text-sm text-slate-500">Saturday, 30 Aug · 14:32 IST</p></div></div><StatusBadge tone="blue">Live simulated network</StatusBadge></header><main id="main-content" className="mx-auto max-w-7xl p-4 sm:p-7"><Outlet/></main></div></div><Toast/></div>; }
export function Placeholder({ title, group }: { title: string; group: string }) { const [open, setOpen] = useState(false); return <div className="space-y-6"><div><p className="label">{group}</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">Foundation route ready for the MediMatch prototype workflow.</p></div><div className="rounded-xl border border-slate-200 bg-white p-6"><StatusBadge tone="blue">Foundation placeholder</StatusBadge><h2 className="mt-4 font-semibold">{title} is ready for implementation</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Shared layout, navigation, typed mock data, role switching, demo state, notifications, and modal systems are established before feature screens are added.</p><button onClick={() => setOpen(true)} className="mt-5 inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold"><Info size={16}/>View prototype safety note</button></div><Modal open={open} title="Prototype safety" onClose={() => setOpen(false)}>Prototype data — not for clinical use. MediMatch coordinates reported capacity and professional confirmation; it does not diagnose, treat, or autonomously choose a hospital.</Modal></div>; }
